server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    resolver 8.8.8.8 valid=30s ipv6=off;

    location /api/ {
        set $backend "${BACKEND_URL}";
        proxy_pass $backend;
        proxy_ssl_server_name on;
    }

    # React Router — serve index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
