server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass ${BACKEND_URL}/api/;
    }

    # React Router — serve index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
